from typing import Any, Protocol


class Service(Protocol):
    async def read(self, id: int) -> Any: ...

    async def create(self, schema: Any) -> Any: ...

    async def update(self, id: int, schema: Any) -> Any: ...

    async def update_attr(self, id: int, attr: str, value: Any) -> Any: ...

    async def put_update(self, id: int, schema: Any) -> Any: ...

    async def delete(self, id: int) -> Any: ...
