name: pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ENV: test
      DB_USER: test
      DB_PASSWORD: test
      DB_HOST: localhost
      DB_PORT: 5432
      DB: postgresql
      DB_URI_SYNC: 'postgresql+psycopg2://test:test@localhost:5432/postgresql'
      SECRET_KEY: d9S0i3pZEjTJlvAf5fqaGE3kkYn6n

    strategy:
      matrix:
        python-version: ["3.13"]

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test-fca
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set Python version
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies (dev)
        working-directory: src
        run: uv sync --dev

      - name: Run pytest
        working-directory: src
        run: uv run pytest -p no:twisted -p no:tornasync ../tests
